from .config import ExperimentConfig, GeometryConfig, ModelConfig, TrainingConfig
from .evaluation import EvaluationResult, InferenceResult, evaluate, infer
from .model import NeuralCellularAutomaton
from .tape import (
    TERNARY_THRESHOLD,
    InterpretedTape,
    TapeLayout,
    binary_to_integer,
    encode_strings,
    integer_to_binary,
    interpret_tape,
    quantize,
    tensor_to_symbols,
)
from .tasks import (
    StringExample,
    StringTask,
    TaskDataset,
    addition_task,
    bitwise_not_task,
    parity_task,
    reverse_task,
    semantic_correct,
)
from .training import (
    LossComponents,
    SeedResult,
    StepMetrics,
    Trainer,
    load_model,
    supervised_loss,
    train_seeds,
)
from .validation import ValidationReport, validate_experiment
from .visualize import evolution_phase, rollout_rgb, save_gif

__all__ = [
    "TERNARY_THRESHOLD",
    "EvaluationResult",
    "ExperimentConfig",
    "GeometryConfig",
    "InferenceResult",
    "InterpretedTape",
    "LossComponents",
    "ModelConfig",
    "NeuralCellularAutomaton",
    "SeedResult",
    "StepMetrics",
    "StringExample",
    "StringTask",
    "TapeLayout",
    "TaskDataset",
    "Trainer",
    "TrainingConfig",
    "ValidationReport",
    "addition_task",
    "binary_to_integer",
    "bitwise_not_task",
    "encode_strings",
    "evaluate",
    "infer",
    "integer_to_binary",
    "interpret_tape",
    "load_model",
    "parity_task",
    "quantize",
    "reverse_task",
    "semantic_correct",
    "supervised_loss",
    "tensor_to_symbols",
    "train_seeds",
    "validate_experiment",
    "evolution_phase",
    "rollout_rgb",
    "save_gif",
]
